title: Tiago Ruas
email: skatiruas@gmail.com
baseurl: ""
url: "https://skatiruas.github.io"
github: "https://github.com/skatiruas"
linkedin: "https://www.linkedin.com/in/tiago-ruas-893160b9"
pt-br:
  personal: Pessoal
  professional: Profissional
en:
  personal: Personal
  professional: Professional

# Build settings
markdown: kramdown
gems:
 - jekyll-coffeescript