title: Tiago Ruas
email: skatiruas@gmail.com
baseurl: ""
personalurl: "/personal"
url: "https://skatiruas.github.io"

# Build settings
markdown: kramdown
gems:
 - jekyll-coffeescript

pt-br:
  personal: Pessoal
  professional: Profissional
en:
  personal: Personal
  professional: Professional